const jokes = [
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why was the math book sad? Because it had too many problems.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the kid cross the playground? To get to the chicken on the other side!",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "Why did the coffee file a police report? It got mugged.",
    "Why did the cookie go to the doctor? Because it was feeling crumbly.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
    "Why was the belt sent to jail? For holding up pants.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "Why did the tomato turn green? Because it wasn't ripe yet.",
    "Why did the girl bring lipstick and eye shadow to school? She had a make-up exam!",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "Why did the duck go to the bank? To get a bill.",
    "What do you call a fake noodle? An impasta.",
    "Why did the crab never share? Because he was shellfish.",
    "Why was the baseball player a lousy singer? He kept hitting foul balls.",
    "Why did the tomato blush? Because it saw the salad dressing.",
    "What do you call a can opener that doesn't work? A can't opener.",
    "Why did the toilet paper roll down the hill? To get to the bottom.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "Why did the man put his money in the freezer? He wanted cold hard cash!",
    "Why don't seagulls fly by the bay? Because then they'd be bagels.",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "Why did the dinosaur cross the road? Chickens weren't invented yet.",
    "Why do golfers wear two pairs of pants? In case they get a hole in one.",
    "Why did the man run around his bed? To get some exercise.",
    "Why do bees hum? Because they don't know the words.",
    "Why did the melon go on vacation? Because it wanted to get away from it all.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the cat go to Minnesota? To get a mini soda.",
    "Why did the girl stare at the carton of orange juice? Because it said concentrate!",
    "Why did the scarecrow win an award? Because he was outstanding in his field.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the boy bring a ladder to school? He wanted to climb the social ladder.",
    "Why did the fish blush? Because it saw the ocean's bottom.",
    "Why did the man wear his wedding ring on the wrong finger? Because he was married to the wrong woman.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "Why did the crab never share? Because he was shellfish.",
    "Why did the bee go to the doctor? It had hives.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "Why did the woman go to the bank with a hammer? She wanted to start a savings account.",
    "Why did the boy sprinkle sugar on his pillow before he went to sleep? So he could have sweet dreams.",
    "Why did the cow go to outer space? To see the moooon.",
    "Why was the belt arrested? For holding up pants.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why did the music teacher need a ladder? To reach the high notes.",
    "Why was the math book sad? Because it had too many problems.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the cookie go to the doctor? Because it was feeling crumbly.",
    "Why did the duck go to the bank? To get a bill.",
    "Why did the coffee file a police report? It got mugged.",
    "Why did the toilet paper roll down the hill? To get to the bottom.",
    "Why did the man put his money in the freezer? He wanted cold hard cash!",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "Why did the girl bring lipstick and eye shadow to school? She had a make-up exam!",
    "Why did the turtle cross the road? To get to the Shell station.",
    "Why don't seagulls fly by the bay? Because then they'd be bagels.",
    "Why did the hipster burn his tongue? He drank his coffee before it was cool.",
    "Why did the tomato turn green? Because it wasn't ripe yet.",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why did the chicken cross the playground? To get to the other slide!",
    "Why did the kid cross the playground? To get to the chicken on the other side!",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the coffee file a police report? It got mugged.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "Why was the belt sent to jail? For holding up pants.",
    "Why did the chicken go to the séance? To talk to the other side.",
    "Why was the math book sad? Because it had too many problems.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "Why did the bicycle fall over? Because it was two-tired.",
    "What do you call a bear with no teeth? A gummy bear!"]



function tellJoke() {
    const jokeIndex = Math.floor(Math.random() * jokes.length);
    const joke = jokes[jokeIndex];
    const jokeElement = document.getElementById("joke");
    jokeElement.innerText = joke;
  }